#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="$ROOT_DIR/.env"
ENV_EXAMPLE="$ROOT_DIR/.env.example"
COMPOSE_FILE="$ROOT_DIR/docker/docker-compose.yml"
APP_JAR_GLOB="$ROOT_DIR/target/islamophobia-detector-*.jar"

if [[ -x "$ROOT_DIR/mvnw" ]]; then
  MAVEN_CMD=("$ROOT_DIR/mvnw")
else
  MAVEN_CMD=(mvn)
fi

if docker compose version >/dev/null 2>&1; then
  COMPOSE_CMD=(docker compose)
elif command -v docker-compose >/dev/null 2>&1; then
  COMPOSE_CMD=(docker-compose)
else
  COMPOSE_CMD=()
fi

info() { printf '\033[1;34m[info]\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m[warn]\033[0m %s\n' "$*"; }
error() { printf '\033[1;31m[error]\033[0m %s\n' "$*"; }

command_exists() {
  command -v "$1" >/dev/null 2>&1
}

compose() {
  if [[ ${#COMPOSE_CMD[@]} -eq 0 ]]; then
    error "Docker Compose is not available. Install Docker Desktop or docker-compose first."
    exit 1
  fi
  "${COMPOSE_CMD[@]}" -f "$COMPOSE_FILE" "$@"
}

ensure_env_file() {
  if [[ ! -f "$ENV_FILE" ]]; then
    cp "$ENV_EXAMPLE" "$ENV_FILE"
    info "Created $ENV_FILE from .env.example"
  fi
}

prompt_with_default() {
  local message="$1"
  local default_value="$2"
  local value
  read -r -p "$message [$default_value]: " value
  if [[ -z "$value" ]]; then
    value="$default_value"
  fi
  printf '%s' "$value"
}

prompt_secret_with_default() {
  local message="$1"
  local default_value="$2"
  local value
  read -r -s -p "$message [hidden]: " value
  printf '\n' >&2
  if [[ -z "$value" ]]; then
    value="$default_value"
  fi
  printf '%s' "$value"
}

load_env() {
  ensure_env_file
  set -a
  # shellcheck disable=SC1090
  source "$ENV_FILE"
  set +a
}

doctor() {
  info "Workspace: $ROOT_DIR"
  for tool in java mvn docker python3 curl; do
    if command_exists "$tool"; then
      printf '  [ok] %s\n' "$tool"
    else
      printf '  [missing] %s\n' "$tool"
    fi
  done

  if [[ -x "$ROOT_DIR/mvnw" ]]; then
    printf '  [ok] mvnw\n'
  fi

  if [[ ${#COMPOSE_CMD[@]} -gt 0 ]]; then
    printf '  [ok] docker compose\n'
  else
    printf '  [missing] docker compose\n'
  fi

  if command_exists ollama; then
    printf '  [ok] ollama\n'
  else
    printf '  [optional] ollama (required only when LLM_PROVIDER=ollama)\n'
  fi

  cat <<'EOF'

Recommended installs on macOS with Homebrew:
  brew install openjdk@17 maven jq
  brew install --cask docker
  brew install ollama
EOF
}

init_env() {
  ensure_env_file

  local run_mode provider openai_key openai_model ollama_host ollama_model database_url database_user database_password sample_data fetch_enabled backfill_enabled

  run_mode="$(prompt_with_default 'Run mode (local|docker)' 'local')"
  provider="$(prompt_with_default 'LLM provider (none|openai|ollama)' 'none')"
  openai_key="${OPENAI_API_KEY:-}"
  openai_model="${OPENAI_MODEL:-gpt-4o}"

  if [[ "$provider" == "openai" ]]; then
    openai_key="$(prompt_secret_with_default 'OpenAI API key' "$openai_key")"
    openai_model="$(prompt_with_default 'OpenAI model' "$openai_model")"
  fi

  if [[ "$run_mode" == "docker" ]]; then
    ollama_host_default="http://ollama:11434"
    database_url_default="jdbc:postgresql://postgres:5432/islamophobia_detector"
  else
    ollama_host_default="http://localhost:11434"
    database_url_default="jdbc:postgresql://localhost:5432/islamophobia_detector"
  fi

  ollama_host="$(prompt_with_default 'Ollama host' "${OLLAMA_HOST:-$ollama_host_default}")"
  ollama_model="$(prompt_with_default 'Ollama model' "${OLLAMA_MODEL:-llama3.1}")"
  database_url="$(prompt_with_default 'Database JDBC URL' "${DATABASE_URL:-$database_url_default}")"
  database_user="$(prompt_with_default 'Database username' "${DATABASE_USERNAME:-postgres}")"
  database_password="$(prompt_secret_with_default 'Database password' "${DATABASE_PASSWORD:-postgres}")"
  sample_data="$(prompt_with_default 'Seed sample data on empty DB? (true|false)' "${APP_SAMPLE_DATA_ENABLED:-true}")"
  fetch_enabled="$(prompt_with_default 'Enable background feed fetching? (true|false)' "${APP_CONTENT_FETCH_ENABLED:-true}")"
  backfill_enabled="$(prompt_with_default 'Enable background analysis backfill? (true|false)' "${APP_CONTENT_BACKFILL_ENABLED:-true}")"

  cat > "$ENV_FILE" <<EOF
# Generated by scripts/onboard.sh on $(date '+%Y-%m-%d %H:%M:%S')
LLM_PROVIDER=$provider
OPENAI_API_KEY=$openai_key
OPENAI_MODEL=$openai_model
OPENAI_TEMPERATURE=${OPENAI_TEMPERATURE:-0.3}
OLLAMA_HOST=$ollama_host
OLLAMA_MODEL=$ollama_model
OLLAMA_TEMPERATURE=${OLLAMA_TEMPERATURE:-0.3}
DATABASE_URL=$database_url
DATABASE_USERNAME=$database_user
DATABASE_PASSWORD=$database_password
JPA_DDL_AUTO=${JPA_DDL_AUTO:-update}
SHOW_SQL=${SHOW_SQL:-false}
SERVER_PORT=${SERVER_PORT:-8080}
LOG_LEVEL_ROOT=${LOG_LEVEL_ROOT:-INFO}
LOG_LEVEL_APP=${LOG_LEVEL_APP:-DEBUG}
LOG_FILE_PATH=${LOG_FILE_PATH:-/var/log/islamophobia-detector/app.log}
APP_CONTENT_FETCH_ENABLED=$fetch_enabled
APP_CONTENT_BACKFILL_ENABLED=$backfill_enabled
APP_SAMPLE_DATA_ENABLED=$sample_data
APP_CONTENT_FETCH_TIMEOUT=${APP_CONTENT_FETCH_TIMEOUT:-30}
APP_CONTENT_MAX_LENGTH=${APP_CONTENT_MAX_LENGTH:-50000}
APP_FEEDBACK_MAX_PER_IP=${APP_FEEDBACK_MAX_PER_IP:-5}
APP_FEEDBACK_BLOCK_DURATION=${APP_FEEDBACK_BLOCK_DURATION:-60}
EOF

  info "Updated $ENV_FILE"
}

build_app() {
  info "Building the application"
  (cd "$ROOT_DIR" && "${MAVEN_CMD[@]}" clean package)
}

pull_model() {
  load_env
  local model="${OLLAMA_MODEL:-llama3.1}"

  if command_exists ollama; then
    info "Pulling Ollama model locally: $model"
    ollama pull "$model"
    return
  fi

  if command_exists docker; then
    compose up -d ollama
    info "Waiting for Dockerized Ollama to start"
    sleep 5
    docker exec islamophobia-ollama ollama pull "$model"
    return
  fi

  warn "Neither local Ollama CLI nor Dockerized Ollama is available."
}

up_stack() {
  load_env
  compose up -d postgres prometheus grafana jaeger

  if [[ "${LLM_PROVIDER:-none}" == "ollama" ]]; then
    compose up -d ollama
    pull_model || true
  fi

  info "Starting application stack"
  compose up -d --build app
  services
}

down_stack() {
  compose down
}

find_built_jar() {
  local jar
  jar="$(find "$ROOT_DIR/target" -maxdepth 1 -name 'islamophobia-detector-*.jar' ! -name '*.original' | head -n 1)"
  if [[ -z "$jar" ]]; then
    error "Built jar not found. Run '$0 build' first."
    exit 1
  fi
  printf '%s' "$jar"
}

run_local() {
  load_env

  export DATABASE_URL="${DATABASE_URL/postgres:/localhost:}"
  export OLLAMA_HOST="${OLLAMA_HOST/ollama:/localhost:}"

  build_app
  local jar
  jar="$(find_built_jar)"
  info "Running $jar locally"
  java -jar "$jar"
}

services() {
  cat <<'EOF'
Services and useful URLs
------------------------
App UI/API     : http://localhost:8080
Health         : http://localhost:8080/actuator/health
Prometheus     : http://localhost:9090
Grafana        : http://localhost:3000
Jaeger         : http://localhost:16686
PostgreSQL     : localhost:5432 (postgres/postgres by default)
Ollama         : http://localhost:11434

Notes:
- Grafana credentials are not overridden in docker-compose today; with the stock image,
  first login is usually admin/admin and Grafana may immediately ask for a password reset.
- If sample data is enabled, the first boot seeds synthetic examples without source links.
- Real feed content arrives via the RSS fetcher and then moves through the backfill scheduler.
EOF
}

usage() {
  cat <<EOF
Usage: $(basename "$0") <command>

Commands:
  doctor       Check local dependencies and suggest installs
  init-env     Interactively create/update .env
  build        Build the project with Maven
  pull-model   Pull the configured Ollama model
  up           Start the Docker Compose stack
  down         Stop the Docker Compose stack
  run-local    Build and run the app locally using .env
  services     Print service URLs and default credentials
EOF
}

main() {
  local command="${1:-help}"
  case "$command" in
    doctor) doctor ;;
    init-env) init_env ;;
    build) build_app ;;
    pull-model) pull_model ;;
    up) up_stack ;;
    down) down_stack ;;
    run-local) run_local ;;
    services) services ;;
    help|-h|--help) usage ;;
    *)
      error "Unknown command: $command"
      usage
      exit 1
      ;;
  esac
}

main "$@"

